### ISSUE TITLE
As a player, I want to see my opponents move (result), so that I can strategize my own

### ISSUE THREAD

**Issue by carolernst-uzh** [sopra-fs23-group-37/client#129]
e.g. display in a little box what they did, which cards

-- goal: by 3 may eod

**Comment by carolernst-uzh** [comment]
e.g. display in a little box what they did, which cards

**Comment by bbajrari** [comment]
closed in https://github.com/sopra-fs23-group-37/client/commit/089ced9631e0203e9d50b76abb4966e71e150fe4
