### ISSUE TITLE
Unselect the cards on table after an errormessage :invalid Move

### ISSUE THREAD

**Issue by Sinthuyan97** [sopra-fs23-group-37/client#228]
Example:
1) The user selects 2 cards from the table (8+A).
2) The user attempts to collect these cards with a total value of 10.
3) An error message appears (Invalid Move)
4) The user clicks "OK."
5) **Bug**: The cards are still selected on the table.
6) Now, the user tries to collect those selected cards with 9
7) Instead of taking the 8 and A from table , a 9 is placed on the table.

**Comment by carolernst-uzh** [comment]
solved in commit https://github.com/sopra-fs23-group-37/client/pull/229/commits/9cb7c107a678f0c877fc19441d674a5e50e3bbf8
